version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://54.145.74.209:27017/BlogDB?directConnection=true&serverSelectionTimeoutMS=2000

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - REACT_APP_API=http://54.145.74.209:3001/api

volumes:
  data:
  logs:
