version: "3.8"
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./api:/app
    environment:
      - MONGO_URL=mongodb+srv://ashwin:ashwingg123@cluster0.cjcyr.mongodb.net/devOps?retryWrites=true&w=majority

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - REACT_APP_API=http://54.145.74.209:3001/api

volumes:
  data:
  logs:
